### ISSUE TITLE
ERROR when start up

### ISSUE THREAD

**Issue by Radiation-pi** [NewAmazingPVP/ProxyPlayerNotify#10]
https://pastebin.com/BwKVMGmK
	
When I download and restart my server this ERROR happens.

I tried to use velocity-3.3.0 and velocity-3.4.0-SNAPSHOT-450, it not works

**Comment by NewAmazingPVP** [comment]
@Radiation-pi Thank you for pointing this out! It turns out that this was another silly yet critical bug. Here's the fixed [build](https://cdn.discordapp.com/attachments/1306686797346111528/1307468658770972723/ProxyPlayerNotify-2.3.2.jar?ex=673a6a93&is=67391913&hm=85c554d974bee556707d21fefcdced94e471cf48b54fc62248e66b145108200c&). Please try it out and let me know if it works as intended. Sorry for the inconveniences!

**Comment by NewAmazingPVP** [comment]
Please let me know if there are any other issues!
