### ISSUE TITLE
Network join message sometimes doesn't appear

### ISSUE THREAD

**Issue by Ben569483** [NewAmazingPVP/ProxyPlayerNotify#8]
Hello, sometimes the network join message doesn't appear in chat. Everything else works fine. I'm not really entirely sure what would be the best way to show the issue, so I attached this screenshot, where I repeatedly joined/left my server on my alt. There were no permission or configuration changes between any of these logins/logouts. The screenshot shows that I had to login and out 9 times before it showed the network join message. (btw don't ask about my alt's name, it's a long story haha)
![image_2024-09-21_141812860](https://github.com/user-attachments/assets/6273577b-43dc-49e1-9dab-e84f2f5fb53c)

**Comment by NewAmazingPVP** [comment]
@Ben569483 Thank you for the descriptions of the problem. I suspect this is because of the delay the join message is sent at. It's not able to get to the server the player joined at and thus doesn't send the message. Therefore, in the version this [build](https://discord.com/channels/1103464645420912671/1278238293028503628/1286516153832964107), I have added ``join_message_delay = 25`` option in the config (you will have to regenerate it) where you should set the delay to the right value, ideally around 30 ticks or at whatever higher value it needs to be to show the messages properly. Please let me know if it works as intended after you have tried it out.

**Comment by Ben569483** [comment]
The link doesn't seem to work, it takes me to a Discord link in your server but it takes me to the rules channel.

**Comment by NewAmazingPVP** [comment]
@Ben569483 Sorry for that, I accidentally linked to the message where the build was posted, not the build itself. Try this [link](https://cdn.discordapp.com/attachments/1103725182314614834/1287430889697181848/ProxyPlayerNotify-bugFix.jar?ex=66f184f3&is=66f03373&hm=53c9749183a87a64265ff6442cc45e24477b89499a05045aadf5349840505f13&)

**Comment by Ben569483** [comment]
Can confirm it now works perfectly after a bit of configuration. I'm using 40 ticks delay and it works perfectly. Thanks!
![image](https://github.com/user-attachments/assets/0d7f7927-7f1e-4b0b-b1d2-f3ed7105c474)

**Comment by NewAmazingPVP** [comment]
That's great to here. I am going to add a feature where if it just sends a "connected to network" message and doesn't have the serverName placeholder in it, then the message can be sent with no delay since it will not have to wait to get the server. I'll send the build here when its done.

**Comment by Ben569483** [comment]
Alright, sounds good, thank you
